name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        uses: CultureHQ/actions-yarn@v1.0.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          args: install --frozen-lockfile --ignore-scripts
      - name: Lint
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: lint
      - name: Test
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: test

  publish-npm:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        uses: CultureHQ/actions-yarn@v1.0.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          args: install --frozen-lockfile --ignore-scripts
      - name: Build
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: build
      - name: Publish
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  
  publish-github:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
